# Generated by Django 3.2 on 2021-06-11 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0076_auto_20210420_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='tipo',
            field=models.TextField(choices=[('A', 'Actividad'), ('P', 'Pago Actividad')], default='A'),
        ),
    ]
