# Generated by Django 2.1.15 on 2022-07-14 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0078_actividadfile'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActividadSong',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.FileField(default='', upload_to='files/', verbose_name='CancionActividad')),
                ('act', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='canciones', to='web.Actividad')),
            ],
            options={
                'verbose_name': 'Cancion activdad',
                'verbose_name_plural': 'Canciones de actividad',
            },
        ),
    ]
